// Mocks generated by Mockito 5.4.6 from annotations
// in catencyclopedia/test/domain/usecases/get_breed_search_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:catencyclopedia/core/error/failures.dart' as _i5;
import 'package:catencyclopedia/data/models/cat_breed_model.dart' as _i6;
import 'package:catencyclopedia/domain/entities/cat_breed.dart' as _i7;
import 'package:catencyclopedia/domain/repositories/cat_repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatRepository extends _i1.Mock implements _i3.CatRepository {
  MockCatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CatBreedModel>>> getCatImages({
    int? page = 0,
    int? limit = 100,
    String? breedIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCatImages, [], {
              #page: page,
              #limit: limit,
              #breedIds: breedIds,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.CatBreedModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.CatBreedModel>>(
                    this,
                    Invocation.method(#getCatImages, [], {
                      #page: page,
                      #limit: limit,
                      #breedIds: breedIds,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CatBreedModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getRandomFact() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomFact, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#getRandomFact, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.CatBreed>>> searchBreeds(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchBreeds, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.CatBreed>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.CatBreed>>(
                    this,
                    Invocation.method(#searchBreeds, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.CatBreed>>>);
}
